88/página de listagem vazia de mentoras avaliadoras
aceleradora-TW/acelera-mais-front pull request #102
Opened 2022-05-27 17:16 UTC by MarquesEmiLly

88/pagina de listagem vazia dse mentoras avaliadoras
====
  
### 🆙 CHANGELOG
layout da página de listagem das mentoras avaliadoras

## ⚠️ Me certifico que:

- [ ] Não deixei nenhum novo warning, erro ou console.log nas minhas modificações
- [ ] Fiz deploy para ambiente de teste certificando que o build não quebrou
- [ ] Solicitei PR para duas pessoas
- [ ] Solicitei **code review** para 2 pessoas

## ⚠️ Como testar:

- [ ]  Acessar o link: https://emilly-acelera-mais-front.herokuapp.com/users;
- [ ]  Verificar se o layout da página esta igual a imagem abaixo:
![image](https://user-images.githubusercontent.com/89554752/170757443-0c84ec72-b4cd-4bac-9361-9f7315b7f45f.png)
- [ ] Aplicação não deve conter nenhum erro, warning ou console.log
- [ ] Alteração proposta no card foi implementada

2022-05-27 17:29 UTC, narukaioh commented on src/components/inputs/search/styled.css
> +  justify-content: flex-start;
A centralização do svg é feita pela regra acima

2022-05-27 17:34 UTC, narukaioh commented on src/routes/index.js
> +        <Route path="/users" element={<MentorRegistrationPage />} exact />
Essa rota nao ia ser feita por outro grupo?

2022-05-27 22:58 UTC, narukaioh requested changes

2022-05-27 22:58 UTC, narukaioh commented on src/pages/mentor-registration/index.js
> +// import { Table } from '../../components/table/table'
remover linhda de comentário

2022-05-30 13:06 UTC, MarquesEmiLly commented on src/components/inputs/search/styled.css
> +  justify-content: flex-start;
removido

2022-05-30 13:07 UTC, MarquesEmiLly commented on src/pages/mentor-registration/index.js
> +          <PrimaryButton text={t('user.backButton')} onClick={pageHome} />
foi adicionado link para pagina de login pois a home ainda não foi criada

2022-05-30 13:08 UTC, MarquesEmiLly commented on src/pages/mentor-registration/styled.js
> +export const MentorRegistrationTable = styled(Table)`
foi substituido pelo componente existente

2022-05-30 13:08 UTC, MarquesEmiLly commented on src/routes/index.js
> +        <Route path="/users" element={<MentorRegistrationPage />} exact />
Sim, excluimos agora

2022-05-30 13:08 UTC, MarquesEmiLly commented on src/pages/mentor-registration/index.js
> +// import { Table } from '../../components/table/table'
foi removida

2022-05-30 14:48 UTC, narukaioh requested changes

2022-05-30 14:48 UTC, narukaioh commented on src/pages/mentor-registration/index.js
> +          <PrimaryButton text={t('user.newMentor.text')} onClick={handleSubmit} />
O Link q usamos é a tag <Link to=“” />

2022-05-30 14:48 UTC, narukaioh commented on src/pages/mentor-registration/index.js
> +          <PrimaryButton text={t('user.newMentor.text')} onClick={handleSubmit} />
E ele nao pode ser fixado para acelera-mais, ele precisa ser relativo ao site do ambiente

2022-05-30 14:48 UTC, narukaioh commented on src/pages/mentor-registration/styled.js
> +   Table{
Sobre o nome das pastas, essa pagina nao é apenas sobre cadastro, ela tb tem outras funcionalidades.

2022-05-31 14:03 UTC, MarquesEmiLly commented on src/pages/mentor-registration/styled.js
> +   Table{
quando o nome do arquivo é alterado, o layout quebra completamente

2022-06-01 16:52 UTC, nicoledbianchin approved these changes

2022-06-02 14:49 UTC, leonardogomesp approved these changes

2022-06-06 14:02 UTC, merged