94/reescrever mock de toggle row
aceleradora-TW/acelera-mais-front pull request #107
Opened 2022-06-06 17:36 UTC by anajess

94/toggleRow no storybook está com erros devido ao mock que não é compatível com o que é pedido pelo componente
====
  
### 🆙 CHANGELOG

Refatoração do mock de Toggle-Row.

![image](https://user-images.githubusercontent.com/66261917/172209425-7b64951c-2fe0-45a7-a731-3af32348c5c0.png)

## ⚠️ Me certifico que:

- [x] Não deixei nenhum novo warning, erro ou console.log nas minhas modificações
- [x] Fiz deploy para ambiente de teste certificando que o build não quebrou
- [x] Solicitei **code review** para 2 pessoas

## ⚠️ Como testar:

- [x]  Acessar repositório frontend;
- [x]  Ir para branch 94/reescrever mock de toggle row;
- [x]  Fazer o git pull;
- [x]  Rodar yarn storybook;
- [x]  Procurar Toggle-Row no storybook;
- [x] Verificar se não tem mensagem de erro; 
- [x] Aplicação não deve conter nenhum erro, warning ou console.log
- [x] Alteração proposta no card foi implementada

2022-06-06 17:39 UTC, narukaioh requested changes

2022-06-06 18:02 UTC, nicoledbianchin approved these changes

2022-06-06 18:04 UTC, anajess commented on .vscode/settings.json
> +    "files.autoSave": "afterDelay"
Problema resolvido

2022-06-07 13:49 UTC, narukaioh approved these changes

2022-06-07 14:47 UTC, merged