99 botao desabilitar habilitar mentora
aceleradora-TW/acelera-mais-front pull request #127
Opened 2022-06-22 18:50 UTC by drebarcelos

#99 - botao desabilitar habilitar mentora
====
  
### 🆙 CHANGELOG

Adiciona botão de desabilitar/habilitar mentora na página de listagem de mentoras avaliadoras.

## ⚠️ Me certifico que:

- [x] Não deixei nenhum novo warning, erro ou console.log nas minhas modificações
- [x] Fiz deploy para ambiente de teste certificando que o build não quebrou
- [x] Solicitei **code review** para 2 pessoas
- [ ] Solicitei **QA** para 2 pessoas
- [ ] Obtive aprovação de QA e posso fazer merge

## ⚠️ Como testar:

- [x] Acessar o link: https://andressa-acelera-mais-front.herokuapp.com
       Login: andressa.barcelos26@gmail.com
      Senha: lslusyqwso
- [x] Clique no botão 'gerenciamento de mentoras'
- [x] Verifique se o botão de habilitar/desabilitar mentora esta como na imagem:

![image](https://user-images.githubusercontent.com/66261917/173070721-ca2a2d59-127e-4518-beeb-06afd4307551.png)

![image](https://user-images.githubusercontent.com/66261917/173070781-fd5c8ec9-3a35-4aad-b107-a21fcc18909f.png)
- [x] Clique no botão "Habilitar" e veja se vai abrir um alert de confirmação "Tem certeza que deseja habilitar essa mentora?"
- [x] Clique em ok e confirme para habilitar mentora
- [x] Clique em inspecionar/rede/user/resposta e verifique se a flag foi alterada para `'user-enabled'`
![image](https://user-images.githubusercontent.com/81838296/175997149-5519567b-f54a-46c2-8052-7e8975ba6f59.png)

- [x] Atualize a página e verifique se a alteração do botão continua salvo
- [x] Clique no botão "Desabilitar" e veja se vai abrir um alert de confirmação "Tem certeza que deseja desabilitar essa mentora?"
- [ ] Clique em ok e confirme para desabilitar mentora
- [ ] Clique em inspecionar/rede/user/resposta e verifique se a flag foi alterada para `'user-disabled'`
- [ ] Atualize a página e verifique se a alteração do botão continua salvo
- [ ] Aplicação não deve conter nenhum erro, warning ou console.log
- [ ] Alteração proposta no card foi implementada

2022-06-27 17:27 UTC, leonardogomesp commented on src/components/toggle/styled.js
> +// const ButtonEnabled = styled.button`
pq estamos mantendo essas regras comentadas?

2022-06-27 17:35 UTC, drebarcelos commented on src/components/toggle/styled.js
> +// const ButtonEnabled = styled.button`
comentários retirados

2022-06-27 17:35 UTC, leonardogomesp approved these changes

2022-06-27 17:50 UTC, narukaioh requested changes

2022-06-27 17:50 UTC, narukaioh commented on src/components/toggle/styled.js
> +border: 1px solid #d3d3d3;
Nessa linha, existe uma color #d3d3d3 e na linha 12, existe um border-color: rgb(102,102,255)
tem duplicação aqui

2022-06-27 17:50 UTC, narukaioh commented on src/components/toggle/index.js
> +    on: 'On',
Esse atributo label, não está sendo utilizado. Porem deveríamos pensar em refatorar o botão toggle para ter uma lógica independente do "user"

2022-06-27 17:50 UTC, narukaioh commented on src/components/toggle/index.js
> +  const alert = async (msg) => {
Essa lógica poderia ser passada por parâmetro do componente, assim conseguiríamos deixar esse componente mais genérico

2022-06-29 14:32 UTC, narukaioh approved these changes

2022-06-29 14:32 UTC, narukaioh commented on src/components/toggle/index.js
> +    on: 'toggleButton.on',
essas palavras " toggleButton.on" e "toggleButton.off" existem no nosso dicionario pt-br e en-us?

2022-07-04 12:12 UTC, merged