111/forcar troca de senha
aceleradora-TW/acelera-mais-front pull request #130
Opened 2022-06-27 16:52 UTC by MarquesEmiLly

#111 Forçar troca de senha
====
  
### 🆙 CHANGELOG

- Criação da pagina com a rota password-reset
- Após o primeiro login do mentor avaliador ele sera forçado a trocar a senha
- Após a troca de senha também sera trocado a flag para user-enabled

## ⚠️ Me certifico que:

- [ ] Não deixei nenhum novo warning, erro ou console.log nas minhas modificações
- [ ] Fiz deploy para ambiente de teste certificando que o build não quebrou
- [ ] Solicitei **code review** para 2 pessoas
- [ ] Solicitei **QA** para 2 pessoas
- [ ] Obtive aprovação de QA e posso fazer merge

## ⚠️ Como testar:

- [ ] Acessar o link: https://emilly-acelera-mais-front.herokuapp.com/
- [ ] Fazer login com seu usuario do banco e senha
- [ ] A pagina deverá estar igual a imagem abaixo : 
![image](https://user-images.githubusercontent.com/89554752/175992265-25c160d7-95a2-48e4-9797-72f5026bc25e.png)

 - [ ] Teste com senhas diferentes e confirme se aparece um alert como no exemplo abaixo: 
![image](https://user-images.githubusercontent.com/89554752/175992616-9822af4e-bdab-4dce-b5ed-e437ea893512.png)
 - [ ] Fazer a mudança de senha (com as senhas iguais sem erro)
 - [ ] Verificar se foi salvo com sucesso e a senha realmente foi alterada
 - [ ] Aplicação não deve conter nenhum erro, warning ou console.log
 - [ ] Alteração proposta no card foi implementada

2022-06-27 17:31 UTC, leonardogomesp approved these changes

2022-06-27 17:59 UTC, narukaioh requested changes

2022-06-27 17:59 UTC, narukaioh commented on src/pages/password-reset/styled.js
> +export const ContainerReset = style.div`
Precisamos criar um código para melhorar esse estilo, ele é bem parecido com o que ja temos nas modais e está sendo repetido aqui. Seria legal criar um card de débito técnico explicando a necessidade de refatorar esse arquivo

2022-06-27 17:59 UTC, narukaioh commented on src/routes/index.js
> +        <Route path="/password-reset/:id" element={<Reset />} exact />
essa rota deveria ser /user/password-reset/:id

deveria estar dentro do bloco

```javascript

        <Route path="/user" element={<IsAuth />}>
          <Route path="/user" element={<MentorPage />} exact />
          <Route path="/user/password-reset/:id" element={<UserChangePasswordPage />} exact />
        </Route>
```

2022-06-27 18:39 UTC, MarquesEmiLly commented on src/pages/password-reset/styled.js
> +export const ContainerReset = style.div`
feito

2022-06-28 17:45 UTC, narukaioh approved these changes

2022-06-28 17:59 UTC, nicoledbianchin approved these changes

2022-07-19 18:47 UTC, merged