134/bug mostra todos os desafios da candidata
aceleradora-TW/acelera-mais-front pull request #143
Opened 2022-07-15 18:55 UTC by LeticiaNunes8

#134 - BUG MOSTRA TODOS OS DESAFIOS DA CANDIDATA
====
  
### 🆙 CHANGELOG

## ⚠️ Me certifico que:

- [ ] Não deixei nenhum novo warning, erro ou console.log nas minhas modificações
- [ ] Fiz deploy para ambiente de teste certificando que o build não quebrou
- [ ] Solicitei **code review** para 2 pessoas
- [ ] Solicitei **QA** para 2 pessoas
- [ ] Obtive aprovação de QA e posso fazer merge

## ⚠️ Como testar:

- [ ] Abrir URL https://leticia-acelera-mais-front.herokuapp.com/home
- [ ] Selecionar Processo Seletivo
- [ ]Criar novo processo
- [ ] Importar a planilha de candidatas: https://docs.google.com/spreadsheets/d/1otPHEw6kHc_Yn3vbTp23fNYJD6MmK-HPl5_GXjZ0kcI/edit?pli=1#gid=202090629
- [ ] Importar a planilha de desafios: https://docs.google.com/spreadsheets/d/13pIgJAPUDk-6OgJ4Ecfm9vCrlzyLLpFp3E25cb-2dF0/edit#gid=549640884
- [ ] Acesse o processo criado
- [ ] Clique em Avaliação e selecione um tipo e cancele
- [ ] Confirme se o tipo está de acordo com o que voce selecionou
- [ ] Clique em Avaliação novamente e selecione um tipo e avalie com nota e feedback
- [ ] Confirme se o o exercício está com o status de fechado, nome do avaliador e a avaliação com feedback

2022-07-15 20:02 UTC, narukaioh requested changes

2022-07-15 20:02 UTC, narukaioh commented on src/pages/evaluation/index.js
> -  const exerciseStatement = challenge.exerciseStatement
Gente, esse "exerciseStatement" precisa existir, isso foi de uma card que foi pedida anteriormente

2022-07-15 20:02 UTC, narukaioh commented on src/pages/hiring-process/components/hiring-process-list/index.js
> +                    {mock.map((a, key) => (<p key={key}>{a.email}</p>))}
Pq estamos usando um "mock" aqui?

2022-07-15 20:02 UTC, narukaioh commented on src/utils/i18next/languages/en/common.json
> +        "title":"Invalid Candidates"
Tem alguma coisa estranha acontecendo aqui, pois esse card parece estar mixado com outras alterações de outro card...

2022-07-18 22:20 UTC, narukaioh approved these changes

2022-07-19 13:11 UTC, nicoledbianchin commented on src/pages/evaluation/index.js
> +  console.log(exercise)
esse log é proposital ou foi deixado pra tras sem querer? 👀

2022-07-19 13:38 UTC, LeticiaNunes8 commented on src/pages/evaluation/index.js
> +  console.log(exercise)
Sem querer. Removemos já kkkk

2022-07-19 17:28 UTC, merged