FEAT: 160/opcao voltar pagina
aceleradora-TW/acelera-mais-front pull request #165
Opened 2022-10-19 17:22 UTC by Renatu5

#160 - opção de voltar nas páginas
====

## ⚠️ Me certifico que:

- [ ] Não deixei nenhum novo warning, erro ou console.log nas minhas modificações
- [ ] Fiz deploy para ambiente de teste certificando que o build não quebrou
- [ ] Solicitei **code review** para 2 pessoas
- [ ] Solicitei **QA** para 2 pessoas
- [ ] Obtive aprovação de QA e posso fazer merge

## ⚠️ Como testar:

- [ ] Acessar o link https://tales-acelera-mais.herokuapp.com/
- [ ] logue com o seguinte usuário:
 - email:  admin@teste6.com
 - senha: 123
- [ ] entre em `Gerenciamento de Mentoras`
- [ ] Verifique se há um botão como este:
![image](https://user-images.githubusercontent.com/97472730/196757330-b1f43e6c-733e-4d38-9fc4-bfa2a1278b0a.png)
- [ ] clique nele, e após isso, ele deve te redirecionar para a página anterior (home)
- [ ] acesse os `Processos Seletivos`, e faça a mesma verificação
- [ ] Após isto, deve acessar ou criar um processo, e verificar se há o mesmo botão dentro dele
- [ ] Dentro dos desafios, tem que haver este mesmo botão, fazendo você voltar para a lista de processos seletivos
- [ ] Aplicação não deve conter nenhum erro, warning ou console.log
- [ ] Alteração proposta no card foi implementada

2022-10-21 16:56 UTC, narukaioh requested changes

2022-10-21 16:56 UTC, narukaioh commented on src/pages/challenges/index.js
> +          <PreventPage />
prevent no ingles, quer dizer "evitar", um botão de voltar se chamaria "BackButton"

2022-10-21 16:56 UTC, narukaioh commented on src/components/preventPage/index.js
> +    <Button icon={icon || faReply} onClick={() => navigate(-1)} className={className} />
Se o botão é apenas para voltar, ele nao precisa receber um "icon" por parametro, basta usar apenas o icone correto

2022-10-24 13:53 UTC, talesacademico commented on src/pages/challenges/index.js
> +          <PreventPage />
Alterações feitas

2022-10-24 13:53 UTC, talesacademico commented on src/components/preventPage/index.js
> +    <Button icon={icon || faReply} onClick={() => navigate(-1)} className={className} />
Alterações feitas

2022-10-24 17:42 UTC, narukaioh requested changes

2022-10-24 17:42 UTC, narukaioh commented on src/pages/hiring-process/index.js
> +          <BackButton />
Então galera, acho que tinha entendendo que iriamos mover o BackButton para dentro do componente Layout, seria interessante vcs ja removerem ele desses locais que está sendo incluido nesse momento

2022-10-24 17:42 UTC, narukaioh commented on src/pages/hiring-process/style.css
> +  justify-content: flex-end;
Outra coisa importante é usar o styled components, nao queremos continuar com o .css

2022-10-24 17:42 UTC, narukaioh commented on src/utils/i18next/languages/en/common.json
> +        "preventPage": "voltar"
vamo la, a palavra "prevent" de novo inserida nesse contexto de "voltar"
outra coisa importante é que nao estou vendo a palavra inserida em um dicionaro pt-br, mas sim em um en.
outra coisa é que a palavra necessita existir em ambos os dicionarios para darmos suporte ao portugues e ao ingles

2022-10-24 17:42 UTC, narukaioh commented on src/components/BackButton/index.js
> +import Button from '../buttons/button'
Criaram um componente global? Então vamos documentar ele no storybook.
Olhem o exemplo dos demais botões para ter noção de como criar a doc pra esse

2022-10-26 14:20 UTC, Willianfreitas01 commented on src/pages/hiring-process/index.js
> +          <BackButton />
Alterações feitas

2022-10-26 14:22 UTC, Willianfreitas01 commented on src/pages/hiring-process/style.css
> +  justify-content: flex-end;
Alterações feitas

2022-10-27 17:04 UTC, narukaioh approved these changes

2022-10-27 18:47 UTC, janinelps approved these changes

2022-10-31 17:55 UTC, merged