161/bug usuário no primeiro acesso não é direcionado para reset de senha
aceleradora-TW/acelera-mais-front pull request #166
Opened 2022-10-21 18:25 UTC by JCdantss

#161 - Bug: usuário no primeiro acesso não é direcionado para reset de senha
====
  
### 🆙 CHANGELOG

- Refatoracao de codigo no arquivo src/pages/authentication/forms/login/index.js
- Refatoracao de codigo no arquivo src/routes/index.js

## ⚠️ Me certifico que:

- [ ] Não deixei nenhum novo warning, erro ou console.log nas minhas modificações
- [ ] Fiz deploy para ambiente de teste certificando que o build não quebrou
- [ ] Solicitei **code review** para 2 pessoas
- [ ] Solicitei **QA** para 2 pessoas
- [ ] Obtive aprovação de QA e posso fazer merge

2022-10-21 19:25 UTC, narukaioh requested changes

2022-10-21 19:25 UTC, narukaioh commented on src/routes/index.js
> +        <Route path="/user" element={<IsAuth mentorType={['admin', 'mentor']} />}>
isso aqui é confuso, acho que nao precisamos desse isAuth nessa rota, mas sim nas rotas interiores

2022-10-25 10:20 UTC, narukaioh approved these changes

2022-10-25 12:00 UTC, janinelps approved these changes

2022-10-25 13:08 UTC, merged