216/feat gerar link de convite mentora avaliadora
aceleradora-TW/acelera-mais-front pull request #169
Opened 2022-10-25 14:34 UTC by EnzoSoares-dev

#216- Listagem de mentora avaliadora: gerar link de convite
====
  
### 🆙 CHANGELOG

- Foi criado uma nova modal presente na pagina de listagem de mentoras, responsável por gerar o link de acesso para novas mentoras. Ele está presente no arquivo src/pages/user/index.js
- Essa modal possui um componente que gera uma requisição para o back-end pedindo um token com tempo de vida estimado de 30 minutos
- Foi criado uma rota que possui uma variável para o token gerado no back-end. Ela esta presente em src/routes/index.js
- Ao acessar o link gerado, será realizada outra requisição ao back-end, comparando se o tempo de vida ainda está válido ou não.
- Se este for válido será apresentado o formulário de cadastro dentro de src/pages/user/forms/user/record
- Caso contrário, ele apresentará uma mensagem de erro falando que o tempo de vida do link expirou e pede para requerir um novo.

## ⚠️ Me certifico que:

- [ ] Não deixei nenhum novo warning, erro ou console.log nas minhas modificações
- [ ] Fiz deploy para ambiente de teste certificando que o build não quebrou
- [ ] Solicitei **code review** para 2 pessoas
- [ ] Solicitei **QA** para 2 pessoas
- [ ] Obtive aprovação de QA e posso fazer merge

## ⚠️ Como testar:

*Esses passos são apenas exemplos*

- [ ] Fazer deploy em ambiente de teste
- [ ] Abrir URL da aplicação de teste
- [ ] Verificar modificação 1
- [ ] Verificar modificação 2
- [ ] Aplicação não deve conter nenhum erro, warning ou console.log
- [ ] Alteração proposta no card foi implementada

2022-10-25 15:12 UTC, narukaioh requested changes

2022-10-25 15:12 UTC, narukaioh commented on src/pages/user/components/link-modal/index.js
> +        title={t(title)}
title é um parametro que poderiamos evitar, já que a ideia é que essa modal seja apenas para criar links. Nao temos um proposito de reutilização aqui, ou seja, nao precisamos parametrizar essa propriedade a mesma coisa a contece abaixo na linha de t(text), também nao existe a necessidade de passar por parametro o texto

2022-10-25 15:12 UTC, narukaioh commented on src/pages/user/forms/user/record.js
> +  return (
Vocês poderiam simplificar mais o return fazendo dessa forma:

```
return (
     { verified ? <Register /> : <Warning /> }
)
```

2022-10-25 15:12 UTC, narukaioh commented on src/pages/user/index.js
> +            <LinkModal
Se seguirem a ideia do design que falei sobre os parametros, esse componente seria apenas chamado assim:
<LinkModal />

Outra coisa é o nome do componente, tentem rebatizar ele para algo mais descritivo sobre o que é o proposito dele. Esse botão funciona como um gerador de LINK para cadastro. Então pensem em algo nessa linha

2022-10-25 15:12 UTC, narukaioh commented on src/routes/index.js
> +          <Route path="/user/:token" element={<RecordPage />} exact />
Estamos falando sobre uma página de cadastro de usuário, acho que o interessante seria tambem evidenciar no nome do componente que ele faz relação ao registro de usuarias ou melhor, mentoras deixando

2022-10-27 16:56 UTC, janinelps approved these changes

2022-10-28 13:08 UTC, narukaioh approved these changes

2022-11-01 14:22 UTC, merged