58/criar componente togglerow
aceleradora-TW/acelera-mais-front pull request #17
Opened 2021-12-01 13:22 UTC by leonardogomesp

#58 - Criar componente togglerow
====

### :up: CHANGELOG

- Implementado função toggle para feedbacks
- Implementado linha que carrega: nome do avaliador, tipo do exercício, status, botão de avaliação e toggle que quando clicado exibe feedback

## :warning: Me certifico que:

- [ ] Não deixei nenhum novo warning, erro ou console.log nas minhas modificações
- [ ] Fiz deploy para ambiente de teste certificando que o build não quebrou
- [ ] Solicitei code review para 2 pessoas
- [ ] Solicitei QA para 2 pessoas
- [ ] Obtive aprovação de QA e posso fazer merge

## :warning: Como testar:

- [ ] 
- [ ]
- [ ] 
- [ ]
- [ ] Aplicação não deve conter nenhum erro, warning ou console.log
- [ ] Alteração proposta no card foi implementada

2021-12-01 13:41 UTC, narukaioh requested changes

2021-12-01 13:41 UTC, narukaioh commented on src/components/togglerow/index.js
> +  if (status === 'status-preparing' || status === 'status-closed') return true
podemos criar um enum para esses status

```
enum {
PREPARING = 'status-preparing'
CLOSED = 'status-closed'
OPENED = 'status-opened'
}
```

e trocar todas as strings por esse enum

2021-12-01 13:41 UTC, narukaioh commented on src/components/togglerow/index.js
> +  const botao = checked ? 'table-row-btn' : 'table-row-btn table-row-btn-checked'
nao devemos usar nomes em portugues no codigo

2021-12-01 13:41 UTC, narukaioh commented on src/components/togglerow/index.js
> +  const botao = checked ? 'table-row-btn' : 'table-row-btn table-row-btn-checked'
tambem podemos simplificar a nomeclatura dessas informações, se elas devem apenas controlar o sentido da seta, entao poderiamos usar feedback-on ou feedback-off

2021-12-01 13:41 UTC, narukaioh commented on src/components/togglerow/index.js
> +  const feedbackLine = checked ? 'table-row-feedback' : 'table-row-feedback table-row-feedback-checked'
mesma coisa para essas classes aqui tb

2021-12-01 13:41 UTC, narukaioh commented on src/components/togglerow/style.css
> +  background-color: rgb(70, 136, 211);
ter um pouco de atenção ao CSS que se repete e tentar fazer ele mais reutilizável, economiza linhas de código

2021-12-01 13:41 UTC, narukaioh commented on src/components/togglerow/togglerow.stories.jsx
> +      <ToggleRow {...args} />
remover essa segunda linha de toggle row

2021-12-01 13:46 UTC, ldiasrs commented on src/components/togglerow/index.js
> +const getStatus = ({ status }) => {
Você acha que esse nome de função mostra realmente o que esta sendo feito? pelo que entendi se o status esta fechado ou em preparação retorna TRUE, nesse caso não acha que o nome da função poderia ser algo mais expressivo nesse sentido? exemplo: 

`isStatusClosedOrPreparing({status})`

2021-12-01 13:46 UTC, ldiasrs commented on src/components/togglerow/index.js
> +const hasFeedback = ({ status }) => {
Aqui a mesma coisa faz sentido hasFeedBack para o uso de status aberto e em preparação?

2021-12-01 13:46 UTC, ldiasrs commented on src/components/togglerow/index.js
> +  const botao = checked ? 'table-row-btn' : 'table-row-btn table-row-btn-checked'
Não faria sentido  ajustar o nome dessa variable para buttonStyle ou algo assim? deixando tudo em EN

2021-12-01 14:25 UTC, ldiasrs commented on src/components/togglerow/index.js
> +const hasFeedback = ({ status }) => {
`isStatusOpenOrPreparing`

2021-12-01 18:25 UTC, ldiasrs approved these changes

2021-12-01 18:32 UTC, narukaioh requested changes

2021-12-01 18:32 UTC, narukaioh commented on public/env.js
> +window.env = {};
esse arquivo nao pode ser comitado

2021-12-02 18:33 UTC, patriciatersariol approved these changes

2021-12-03 12:35 UTC, narukaioh approved these changes

2021-12-03 18:14 UTC, merged