174/mostrar nome da pessoa logada
aceleradora-TW/acelera-mais-front pull request #178
Opened 2022-11-04 16:48 UTC by Cibely87

====
  
### 🆙 CHANGELOG

- Mostrar nome da pessoa logada em texto de saudação.

## ⚠️ Me certifico que:

- [ ] Não deixei nenhum novo warning, erro ou console.log nas minhas modificações
- [ ] Fiz deploy para ambiente de teste certificando que o build não quebrou
- [ ] Solicitei **code review** para 2 pessoas
- [ ] Solicitei **QA** para 2 pessoas
- [ ] Obtive aprovação de QA e posso fazer merge

## ⚠️ Como testar:

- [ ] Acesse o link: 
    - Login: 
    - Senha: 123
- [ ] Clique em "Gerenciamento de mentoras".
- [ ] Aplicação não deve conter nenhum erro, warning ou console.log
- [ ]  Alteração proposta no card foi implementada

2022-11-04 17:18 UTC, narukaioh requested changes

2022-11-04 17:18 UTC, narukaioh commented on src/components/greetingText/index.js
> +  return <Greeting>Seja bem vinde, {nome}</Greeting>
Faltou a tradução dessa frase

2022-11-04 17:18 UTC, narukaioh commented on src/components/layout/style.js
> +margin-left: 1rem;
usamos e pixel as medições de todo o projeto

2022-11-07 18:31 UTC, narukaioh approved these changes

2022-11-07 18:47 UTC, janinelps approved these changes

2022-11-09 18:16 UTC, merged