57/criar componente select
aceleradora-TW/acelera-mais-front pull request #19
Opened 2021-12-02 16:24 UTC by LuizHenrique000

2021-12-02 16:53 UTC, nicoledbianchin commented on package.json
> +    "storybook": "^6.3.12",
acho que nao estamos usando essa dependência, podemos apagar. pra confirmar dá pra rodar no terminal `npm list storybook`, se retornar `empty` pode apagar (dai precisa apagar o package-lock.json, yarn.lock e a pasta node-modules e rodar npm install de novo pra ajustar as dependencias localmente)

2021-12-02 16:53 UTC, nicoledbianchin approved these changes

2021-12-02 17:07 UTC, Jojorel commented on package.json
> +    "storybook": "^6.3.12",
Testamos o npm lista stroybook e voltou a versao 6.4.3 , devemos ainda apagar o "storybook": "^6.3.12"?

2021-12-03 14:48 UTC, leonardogomesp requested changes
esse arquivo env.js não deve ser comitado

2021-12-03 19:02 UTC, leonardogomesp approved these changes

2021-12-06 12:30 UTC, merged