221/salvar dados da pagina de cadastro
aceleradora-TW/acelera-mais-front pull request #192
Opened 2022-11-17 18:25 UTC by talesacademico

#221-Salvar-dados-pagina-cadastro
====

## ⚠️ Me certifico que:

- [ ] Não deixei nenhum novo warning, erro ou console.log nas minhas modificações
- [ ] Fiz deploy para ambiente de teste certificando que o build não quebrou
- [ ] Solicitei **code review** para 2 pessoas
- [ ] Solicitei **QA** para 2 pessoas
- [ ] Obtive aprovação de QA e posso fazer merge

## ⚠️ Como testar:

*Esses passos são apenas exemplos*

- [ ] Fazer deploy em ambiente de teste
- [ ] Abrir URL da aplicação de teste
- [ ] Verificar modificação 1
- [ ] Verificar modificação 2
- [ ] Aplicação não deve conter nenhum erro, warning ou console.log
- [ ] Alteração proposta no card foi implementada

2022-11-22 15:43 UTC, narukaioh requested changes

2022-11-22 15:43 UTC, narukaioh commented on src/pages/user/components/mentor-register/mentorRegister.js
> +      {verify === null ? loading() : messageError()}
basta colocar verify ? loading() : messageError()

2022-11-22 15:43 UTC, narukaioh commented on src/pages/user/components/mentor-register/mentorRegister.js
> +      <h1>Carregando...</h1>
Faltou internacionalização nessa palavra

2022-11-22 15:43 UTC, narukaioh commented on src/pages/user/components/mentor-register/mentorRegister.js
> +const loading = () => {
Componentes iniciam com maiusculas sempre

2022-11-22 15:43 UTC, narukaioh commented on src/pages/user/components/mentor-register/mentorRegister.js
> +const messageError = () => {
Componentes iniciam com maiusculas sempre

2022-11-22 15:43 UTC, narukaioh commented on src/pages/user/forms/user/MentorRegisterPage.js
> +      {verified ? <Register /> : <UseMessageRegisterError verify={verified}/>}
Voces podem fazer toda a gerencia do estado nessa página, ela quem deve saber quando e o que exibir de acordo com esse verified

2022-11-25 17:32 UTC, narukaioh approved these changes

2022-11-25 17:34 UTC, janinelps approved these changes

2022-11-25 17:50 UTC, merged