152/removendo o modal desnecessario de exportação
aceleradora-TW/acelera-mais-front pull request #203
Opened 2022-11-24 12:37 UTC by k-js

#152 - Melhoria: Modal export é necessária? 
====
  
### 🆙 CHANGELOG

- Remoção do modal substituindo pelo componente Button 
- Quando o usuário clicar no botão de export, o download deve iniciar diretamente

## ⚠️ Me certifico que:

- [x] Não deixei nenhum novo warning, erro ou console.log nas minhas modificações
- [ ] Fiz deploy para ambiente de teste certificando que o build não quebrou
- [x] Solicitei **code review** para 2 pessoas
- [x] Solicitei **QA** para 2 pessoas
- [x] Obtive aprovação de QA e posso fazer merge

## ⚠️ Como testar:

- [x] Acessar o front na branch 152/melhoria-modal-export
- [x] Iniciar o Back-end 
- [x] Abrir o Front no navegador
- [x] Fazer login com seu usuário local  
- [x] Entrar na pagina de processos seletivos 
- [x] Clicar no botão exportar dados e o download será feito automaticamente 
- [x] Aplicação não deve conter nenhum erro, warning ou console.log
- [x] Alteração proposta no card foi implementada

2022-11-24 13:33 UTC, narukaioh requested changes

2022-11-24 13:33 UTC, narukaioh commented on src/pages/hiring-process/components/hiring-process-list/index.js
>                    label="Download arquivo csv"
"Download arquivo csv" tem que ser uma palavra no dicionário do ingles e do portugues

2022-11-30 17:14 UTC, k-js commented on src/pages/hiring-process/components/hiring-process-list/index.js
>                    label="Download arquivo csv"
Ajuste resolvido.

2022-11-30 19:27 UTC, narukaioh approved these changes

2022-12-01 16:34 UTC, merged