151/ Refatorar as ações disponíveis na listagem de processos seletivos
aceleradora-TW/acelera-mais-front pull request #214
Opened 2022-12-05 17:23 UTC by vanessalmirante

#151 - Refatorar as ações disponíveis na listagem de processos seletivos
====
  
### 🆙 CHANGELOG
- Remoção do botão de excluir processo seletivo (/hiring-process).
- Criação de função para verificar status do processo seletivo {isHiringProcessOpen()}
- Desabilitação do botão de editar processo seletivo quando este estiver fechado.

## ⚠️ Me certifico que:

- [ ] Não deixei nenhum novo warning, erro ou console.log nas minhas modificações
- [ ] Fiz deploy para ambiente de teste certificando que o build não quebrou
- [ ] Solicitei **code review** para 2 pessoas
- [ ] Solicitei **QA** para 2 pessoas
- [ ] Obtive aprovação de QA e posso fazer merge

## ⚠️ Como testar:

*Esses passos são apenas exemplos*

- [ ] Acessar a branch "151/refatorar-acoes-na-pagina-processos-seletivos" no front-end da aplicação Acelera Mais.
- [ ] Iniciar a aplicação
- [ ] Realizar login com um usuário admin.
- [ ] Ir na página de Processos Seletivos.
- [ ] Verificar que o botão de excluir processo seletivo não existe.
- [ ] Tentar editar um processo seletivo fechado e não obter êxito.
- [ ] Tentar editar um processo seletivo aberto e obter êxito.
- [ ] Aplicação não deve conter nenhum erro, warning ou console.log
- [ ] Alteração proposta no card foi implementada.

2022-12-05 18:09 UTC, narukaioh requested changes

2022-12-05 18:09 UTC, narukaioh commented on src/pages/hiring-process/components/hiring-process-list/index.js
> -      setHiringProcesses(newProcesses)
se foi removido o setHiringProcesses, entao precisa remover tb o que está no parametro.
podemos deletar as variaveis sem uso do codigo

2022-12-05 18:09 UTC, narukaioh commented on src/pages/hiring-process/components/hiring-process-list/index.js
> +  const isHiringProcessOpen = (status) => status === 'status-opened'
outra coisa é que confirmei coma Ju Martins, e esse bloqueio deve ser feito somente quando o processo for fechado, enquanto ele estiver aberto deve permitir a edição.

entao tem q trocar pra `status-closed`

2022-12-08 20:07 UTC, narukaioh approved these changes

2022-12-09 08:03 UTC, janinelps approved these changes

2022-12-09 14:28 UTC, merged