181/logo voltar para tela home - Ajustes
aceleradora-TW/acelera-mais-front pull request #216
Opened 2022-12-06 13:40 UTC by Willianfreitas01

#181  -  Ajustando logo da aceleradora volta para a página inicial 
====
  
### 🆙 CHANGELOG

- Ajustamento a estilização do logo nas telas 

## ⚠️ Me certifico que:

- [x] Não deixei nenhum novo warning, erro ou console.log nas minhas modificações
- [x] Fiz deploy para ambiente de teste certificando que o build não quebrou
- [x] Solicitei **code review** para 2 pessoas
- [ ] Solicitei **QA** para 2 pessoas
- [ ] Obtive aprovação de QA e posso fazer merge

## ⚠️ Como testar:

- [x] acesse a branch #181
- [x] Logar com o seu usuário local
- [x] Verificar se o Logo da aceleradora esta em todas as paginas (menos na tela de cadastro e na de change-password)
- [x] mude a resolução do seu navegador, utilizando o `inspecionar elemento`
- [x] Após clicar no Logo, é redirecionado para a tela home
- [x] Aplicação não deve conter nenhum erro, warning ou console.log
- [x] Alteração proposta no card foi implementada

2022-12-06 14:29 UTC, narukaioh requested changes

2022-12-06 14:29 UTC, narukaioh commented on src/components/logo/styled.js
> +position:absolute;
pq é necessário um position absolute?
Acho que voces podem tentar sem isso

2022-12-06 14:29 UTC, narukaioh commented on src/components/logo/styled.js
> +position:absolute;
usem apenas flex para posicionar as coisas no layout

2022-12-06 14:38 UTC, Willianfreitas01 commented on src/components/logo/styled.js
> +position:absolute;
nós tentamos usar somente o flex, só que ele não corresponde muito bem e a imagem se movimenta pouco do lugar, o position:absolute foi uma forma de driblar os problemas que estava tendo o display flex, assim a gente conseguia ajustar com mais facilidade apenas colocando left e top

2022-12-14 15:44 UTC, narukaioh approved these changes

2022-12-15 16:57 UTC, merged