221/Transformar index.css em styled-components
aceleradora-TW/acelera-mais-front pull request #218
Opened 2022-12-06 14:25 UTC by JeanCastilhos2

…ilhos2

@EnzoSoares-dev

#<NUMERO-DO-CARD> - Titulo do Card
====
  
### 🆙 CHANGELOG

*Esses passos são apenas exemplos*

- Mudança 1
- Mudança 2
- Mudança 3

## ⚠️ Me certifico que:

- [ ] Não deixei nenhum novo warning, erro ou console.log nas minhas modificações
- [ ] Fiz deploy para ambiente de teste certificando que o build não quebrou
- [ ] Solicitei **code review** para 2 pessoas
- [ ] Solicitei **QA** para 2 pessoas
- [ ] Obtive aprovação de QA e posso fazer merge

## ⚠️ Como testar:

*Esses passos são apenas exemplos*

- [ ] Fazer deploy em ambiente de teste
- [ ] Abrir URL da aplicação de teste
- [ ] Verificar modificação 1
- [ ] Verificar modificação 2
- [ ] Aplicação não deve conter nenhum erro, warning ou console.log
- [ ] Alteração proposta no card foi implementada

2022-12-06 19:55 UTC, narukaioh requested changes

2022-12-06 19:55 UTC, narukaioh commented on src/App.js
> +      <GlobalStyle />,
pq tem uma virgula aqui? essa virgula aparecera em todas as paginas

2022-12-07 16:31 UTC, narukaioh approved these changes

2022-12-07 16:33 UTC, janinelps approved these changes

2022-12-08 12:38 UTC, merged