72 b/importar desafios
aceleradora-TW/acelera-mais-front pull request #23
Opened 2021-12-10 14:49 UTC by LuizHenrique000

#72 - Importar desafios (atualização)
====

### 🆙 CHANGELOG

- Feita as alterações solicitadas pela P.O. Ju Martins.
- Implementa mensagem de aviso na modal.

## ⚠️ Me certifico que:

- [ ] Não deixei nenhum novo warning, erro ou console.log nas minhas modificações
- [ ] Fiz deploy para ambiente de teste certificando que o build não quebrou
- [ ] Solicitei code review para 2 pessoas
- [ ] Solicitei QA para 2 pessoas
- [ ] Obtive aprovação de QA e posso fazer merge

## ⚠️ Como testar:

- [ ] Acesse o link https://luiz-acelera-mais-teste.herokuapp.com/
- [ ] Fazer o login ( email: ju@gmail.com // senha: 123456 ).
- [ ] Clicar no botão "Importar desafios" e "importar candidatas".
- [ ] Verificar se abriu uma modal com o seguinte aviso: "Obs: Para finalizar a integração, compartilhe o e-mail: acelera-mais@aceleradora-agil-331516.iam.gserviceaccount.com"

2021-12-10 15:02 UTC, narukaioh requested changes

2021-12-10 15:02 UTC, narukaioh commented on src/components/import-google-sheet/index.js
> +    client.post(`${url}/${id}`, dataGoogleSheet)
`${endpoint}/hiring_process/${id}`

2021-12-10 15:02 UTC, narukaioh commented on src/components/modal/style.css
> +  font-family: "Roboto", sans-serif;
nao existe essa fonte no projeto, seria importante tirar pois ela nao funciona sem a importação

2021-12-10 15:02 UTC, narukaioh commented on src/components/modal/index.js
> +          <p className="modal-reminder">{reminder}</p>
Esse reminder, nao faria escopo da modal, seria uma definicao do Formulario

2021-12-10 17:20 UTC, inglyd commented on src/components/hiring-process-list/index.js
> +                    url={'/candidate/hiring_process'}
ok, feito!

2021-12-10 17:20 UTC, inglyd commented on src/components/hiring-process-list/index.js
> +                    url={'/exercise/hiring_process'}
ok, feito!

2021-12-10 17:21 UTC, inglyd commented on src/components/import-google-sheet/index.js
> +export const ImportGoogleSheet = ({ id = '', url = '' }) => {
ok, feito!

2021-12-10 17:21 UTC, inglyd commented on src/components/import-google-sheet/index.js
> +    client.post(`${url}/${id}`, dataGoogleSheet)
ok, feito!

2021-12-10 17:31 UTC, inglyd commented on src/components/modal/style.css
> +  font-family: "Roboto", sans-serif;
realmente não foi importada, mas estranhamente ele está pegando e foi colocada em outros lugares, mas podemos retirar do nosso

2021-12-10 17:31 UTC, inglyd commented on src/components/modal/index.js
> +          <p className="modal-reminder">{reminder}</p>
então ele ficaria dentro do conteudo da modal?

2021-12-13 11:38 UTC, ldiasrs approved these changes

2021-12-13 16:35 UTC, IngridDuarte approved these changes

2021-12-14 14:04 UTC, narukaioh approved these changes

2021-12-14 14:05 UTC, merged