feat(components/modal): implementa styled components
aceleradora-TW/acelera-mais-front pull request #54
Opened 2022-01-07 14:27 UTC by leonardogomesp

#42 - refact components/modal
====

### 🆙 CHANGELOG

Esses passos são apenas exemplos

- Mudança 1
- Mudança 2
- Mudança 3

## ⚠️ Me certifico que:

- [ ] Não deixei nenhum novo warning, erro ou console.log nas minhas modificações
- [ ] Fiz deploy para ambiente de teste certificando que o build não quebrou
- [ ] Solicitei code review para 2 pessoas
- [ ] Solicitei QA para 2 pessoas
- [ ] Obtive aprovação de QA e posso fazer merge

## ⚠️ Como testar:

Esses passos são apenas exemplos

- [ ] Fazer deploy em ambiente de teste
- [ ] Abrir URL da aplicação de teste
- [ ] Verificar modificação 1
- [ ] Verificar modificação 2
- [ ] Aplicação não deve conter nenhum erro, warning ou console.log
- [ ] Alteração proposta no card foi implementada

2022-01-07 14:53 UTC, narukaioh requested changes

2022-01-07 14:53 UTC, narukaioh commented on src/components/modal/style.js
> +  font-family: Arial, Helvetica, sans-serif;
toda hora to vendo essa font, e depois roboto e depois opens-sans.. nao era pra ter definicao de fonte, pq a gente ja tem isso setado no css da raiz

2022-01-07 20:56 UTC, narukaioh commented
Outra coisa importante, o botão de enviar é azul, nao é default

2022-01-14 15:00 UTC, narukaioh approved these changes

2022-01-17 14:02 UTC, ccarolb approved these changes

2022-01-17 16:13 UTC, merged