61/refact implementar internacionalização i18next em pages/hiring process list/import google sheet
aceleradora-TW/acelera-mais-front pull request #74
Opened 2022-01-21 17:02 UTC by Cibely87

# 61 Implementar internacionalização i18next em Hiring-ProcessList/Import-Google-Shee

# CHANGELOG

- Implementação de internacionalização utilizando i18next no Import Google Sheet.
- Mudança de idioma dentro das caixas de texto em importar candidatas e desafios.
- Mensagens de erro ou envio em outro idioma com o i18next

Me certifico que:

- [ ]  Não deixei nenhum novo warning, erro ou console.log nas minhas modificações.
- [ ]  Fiz deploy para ambiente de teste, certificando que o build não quebrou.
- [ ]  Solicitei code review para 2 pessoas.
- [ ]  Solicitei QA para 2 pessoas.
- [ ]  Obtive aprovação de QA e posso fazer merge.

Como testar:

- [ ]  Acessar link de teste: https://teste-cibely-acelera-mais.herokuapp.com/
- [ ]  Verificar se seu sistema esta correspondente com o idioma do seu navegador. (Portugues ou Ingles)
- [ ]  Efetuar a troca do idioma do seu navegador(ex: de Portugues para inglês ou vice-versa) 
- [ ] Atualizar a pagina de teste
- [ ] Verficar se houve troca de idioma dentro das caixas de texto em Importar Candidatas e Desafios
- [ ] Inserir as URLs
Desafios: https://docs.google.com/spreadsheets/d/1Xn-fcGHuyx4TxzMCqTJ7gmKcMbMdNWR6CBtRHr2v84M/edit#gid=1886435917
Candidatas: https://docs.google.com/spreadsheets/d/172hDo1RvIFpczFvuq3HoAD5wQoB2hBmnBHMoo_MYw8Y/edit#gid=199214593 
- [ ] Conferir se houve troca de idioma dos alerts de sucesso ou não.
- [ ] Verifique se todas as funcionalidades estão funcionando normalmente
- [ ]  Aplicação não deve conter nenhum erro, warning ou console.log
- [ ]  Alteração proposta no card foi implementada

2022-01-21 17:51 UTC, narukaioh requested changes

2022-01-21 17:51 UTC, narukaioh commented on src/utils/i18next/languages/en/common.json
> +        "name": "Name",
a palavra Name nao é traduzida, entao pode remover ela dos arquivos common

2022-01-21 18:01 UTC, narukaioh approved these changes

2022-01-24 12:13 UTC, leonardogomesp approved these changes

2022-01-24 13:38 UTC, merged