64/implementar pagina de exercicios i18n
aceleradora-TW/acelera-mais-front pull request #76
Opened 2022-01-28 14:32 UTC by eluvya

# #64 Refact: implementar internacionalização i18next em pages/evaluation/components/toggle-row

# CHANGELOG

- Implementação de internacionalização utilizando i18next em pages/evaluation/components/toggle-row
- Mudança de idioma em alguns componentes da página de Exercise

## Me certifico que:

- [ ]  Não deixei nenhum novo warning, erro ou console.log nas minhas modificações.
- [ ]  Fiz deploy para ambiente de teste, certificando que o build não quebrou.
- [ ]  Solicitei code review para 2 pessoas.
- [ ]  Solicitei QA para 2 pessoas.
- [ ]  Obtive aprovação de QA e posso fazer merge.

# Como testar:

- [ ]  Acessar link de teste: https://eluvya-acelera-mais-teste.herokuapp.com/
- [ ]  Efetue a troca do idioma do seu navegador (ex: de português para inglês)
- [ ]  Atualize a pagina de teste
- [ ]  Efetue o login (email: ju@gmail.com senha: 123456) e insira um nome de mentora.
- [ ]  Confira se a página de Exercícios está em inglês no campos `tipo` e `avaliador`. Deve aparentar como a imagem abaixo:
![Captura de tela de 2022-01-28 11-25-33](https://user-images.githubusercontent.com/52509940/151564495-ca015e22-4bf2-48c3-8dee-300e1f5a9e20.png)
- [ ]  Verifique se todas as funcionalidades estão funcionando normalmente
- [ ]  Aplicação não deve conter nenhum erro, warning ou console.log
- [ ]  Alteração proposta no card foi implementada

2022-01-28 14:42 UTC, narukaioh requested changes

2022-01-28 14:42 UTC, narukaioh commented on src/components/status/index.js
> +    preparing: 'status.preparing'
por ter renomeado para "preparing" a gente precisa ter certeza que onde está sendo usado o componente de status nao tenha quebrado com essa nova logica. Exemplo: Olhar se na página de HiringProcess, onde existe o componente de status, se ele ta criando com "preparing" ou ainda é "prepairing"

2022-01-28 14:42 UTC, narukaioh commented on src/pages/exercises/components/toggle-row/index.js
>    if (status === statusEnum.PREPARING || status === statusEnum.CLOSED) return true
essa função também está na imagem que enviei para ser refatorada. Observar todas as funções que enviei pois elas precisam dessa refatoração tb

2022-01-28 14:43 UTC, narukaioh commented on src/pages/exercises/components/toggle-row/index.js
>    if (status === statusEnum.PREPARING || status === statusEnum.CLOSED) return true
outrra coisa, é que isso é parte do que eu falei que deveria ser feito apenas no outro commit

2022-01-28 16:54 UTC, eluvya commented on src/components/status/index.js
> +    preparing: 'status.preparing'
o status usado no Hiring Process vem do componente Status que já foi corrigido para preparing

2022-01-28 17:57 UTC, narukaioh requested changes

2022-01-28 17:57 UTC, narukaioh commented on src/pages/exercises/components/toggle-row/index.js
> +const isOpened = ({ status }) => status === statusEnum.OPENED
Notei mais uma melhoria, essas funções precisam estar nessa ordem e notem, estou fazendo o reuso de `isOpened` dentro da outra função `isPreparingOrOpened`
```javascript
const isOpened = ({ status }) => status === statusEnum.OPENED

const isPreparingOrOpened = ({ status }) => isPrepared({ status }) || isOpened({ status })
```

2022-01-28 17:57 UTC, narukaioh commented on src/pages/exercises/components/toggle-row/index.js
> +const isClosedOrPreparing = ({ status }) => isPrepared({ status }) || status === statusEnum.CLOSED
Notei mais uma melhoria, essas funções precisam estar nessa ordem e notem, estou fazendo o reuso de `isClosed` dentro da outra função `isClosedOrPreparing`
```javascript
const isClosed = ({ status }) => status === statusEnum.CLOSED

const isClosedOrPreparing = ({ status }) => isPrepared({ status }) || isClosed({ status })
```

2022-01-31 16:20 UTC, narukaioh approved these changes

2022-01-31 16:38 UTC, janinelps approved these changes

2022-01-31 17:02 UTC, merged