16/editar processo seletivo
aceleradora-TW/acelera-mais-front pull request #8
Opened 2021-11-05 16:47 UTC by eluvya

#16 - Editar processo seletivo
====
  
### 🆙 CHANGELOG

- Implementamos a modal; 
- Foi adicionado o botão Excluir na página de processos seletivos;
- Implementamos o endpoint PATCH;
- Implementamos o endpoint DELETE. 

## ⚠️ Me certifico que:

- [x] Não deixei nenhum novo warning, erro ou console.log nas minhas modificações
- [x] Fiz deploy para ambiente de teste certificando que o build não quebrou
- [ ] Solicitei **code review** para 2 pessoas
- [ ] Solicitei **QA** para 2 pessoas
- [ ] Obtive aprovação de QA e posso fazer merge

## ⚠️ Como testar:

- [ ] URL da aplicação de teste: https://eluvya-acelera-mais-teste.herokuapp.com/hiring-process
- [ ] Verificar se ao clicar em Editar é aberto uma modal
- [ ] Verificar se a ação de editar foi bem sucedida ao clicar no botão Enviar.
- [ ]  Verificar se a ação de excluir foi bem sucedida ao clicar no botão Exlcuir
- [ ] Aplicação não deve conter nenhum erro, warning ou console.log
- [ ] Alteração proposta no card foi implementada.

2021-11-05 16:59 UTC, nicoledbianchin commented on src/components/forms/hiring-process/index.js
> +      <Button classe='button-submit' type="button" text='Enviar' onClick={sendHiringProcess}>
aqui não seria `class`?

2021-11-05 17:01 UTC, nicoledbianchin approved these changes

2021-11-05 17:17 UTC, BrayanArgradem approved these changes

2021-11-08 14:29 UTC, narukaioh approved these changes

2021-11-09 09:21 UTC, narukaioh requested changes

2021-11-09 09:21 UTC, narukaioh commented on src/pages/hiring-process/index.js
> +  }, [hiringProcesses])
acho que a gente nao vai conseguir trabalhar com essa solução que eu sugeri, vamos precisar remover e procurar uma nova solução para atualizar a lista de alguma forma mais simples

2021-11-09 14:40 UTC, merged