77/listagem de exercicios tela avaliacao
aceleradora-TW/acelera-mais-front pull request #84
Opened 2022-03-02 18:45 UTC by janinelps

#77 - Listagem de exercicios tela avaliação
====

### 🆙 CHANGELOG

- Apresentação da lista de exercicios na tela de avaliação conforme a quantidade de exercícios que vier da resposta da API, se tiver apenas 1 exercício, apenas 1 deles deve ser exibido

## ⚠️ Me certifico que:

- [x] Não deixei nenhum novo aviso, erro ou console.log nas minhas modificações
- [x]  Fiz deploy para ambiente de teste certificando que o build não quebrou
- [x]  Solicite uma revisão do código para 2 pessoas
- [ ]  Solicitei QA para 2 pessoas
- [ ]  Obtive aprovação de QA e posso fazer merge

## ⚠️ Como testar:

- [x] Acessar link de teste: https://eluvya-acelera-mais-teste.herokuapp.com/
- [x] Fazer login (e-mail: ju@gmail.com, senha: 123456, nome da mentora: seu nome)
- [ ] Verificar se o layout da pagina apresenta este visual:
Obs: pode estar em inglês
![image](https://user-images.githubusercontent.com/79364568/156426477-a6f7bfca-6066-4d3a-a44b-5bac8b63d573.png))
- [ ] Clicar nos botões e verificar se eles mantém a funcionalidade proposta
- [ ] Aplicação não deve conter nenhum erro, warning ou console.log
- [ ] Alteração proposta no card foi implementada

2022-03-02 19:39 UTC, narukaioh requested changes

2022-03-02 19:39 UTC, narukaioh commented on src/pages/evaluation/styled.js
> +  h1 {
Nesse caso, entendo que vcs moveram a regra de CSS que estava dentro de outro local, é importante que uma vez que a gente move a lógica desse estilo, apaguemos tb o código que não é mais util.

2022-03-02 19:39 UTC, narukaioh commented on src/pages/evaluation/styled.js
>  h1 {
Aqui começa a regra que não é mais util, que estilizava o H1 quando ele estava dentro do Header

2022-03-02 19:39 UTC, narukaioh commented on src/utils/i18next/languages/pt/common.json
> +      "title": "Exercícios",
Eu colocaria "Respostas dos Exercícios"

2022-03-03 12:56 UTC, narukaioh approved these changes

2022-03-03 13:16 UTC, nicoledbianchin approved these changes

2022-03-08 12:27 UTC, merged