78/layout alterar tela desafios
aceleradora-TW/acelera-mais-front pull request #85
Opened 2022-03-15 16:53 UTC by Cibely87

78/layout alterar tela desafios
====

### 🆙 CHANGELOG

- Apresentação da lista de exercícios na tela de desafios conforme a quantidade de exercícios que vier da resposta da API, se tiver apenas 1 exercício, apenas 1 deles deve ser exibido.

## ⚠️ Me certifico que:

- [x] Não deixei nenhum novo aviso, erro ou console.log nas minhas modificações
- [x]  Fiz deploy para ambiente de teste certificando que o build não quebrou
- [ ]  Solicite uma revisão do código para 2 pessoas
- [ ]  Solicitei QA para 2 pessoas
- [ ]  Obtive aprovação de QA e posso fazer merge

## ⚠️ Como testar:

- [ ] Acessar link de teste: https://eluvya-acelera-mais-teste.herokuapp.com/
- [ ] Fazer login (e-mail: ju@gmail.com, senha: 123456, nome da mentora: seu nome)
- [ ] Crie um novo processo seletivo
- [ ] Importe as planilhas atualizadas
   - `CANDIDATAS:` https://docs.google.com/spreadsheets/d/1otPHEw6kHc_Yn3vbTp23fNYJD6MmK-HPl5_GXjZ0kcI/edit?pli=1#gid=202090629
   - `EXERCÍCIOS:` https://docs.google.com/spreadsheets/d/13pIgJAPUDk-6OgJ4Ecfm9vCrlzyLLpFp3E25cb-2dF0/edit#gid=549640884
- [ ] Verificar se o layout da pagina apresenta este visual:
![image](https://user-images.githubusercontent.com/92865717/158428770-8b3d31a5-fc6a-4a6f-bee0-94e24fb82d5e.png)
![image](https://user-images.githubusercontent.com/92865717/158429213-c9854fb8-f14f-4ca5-bac2-b250318ec658.png)
- [ ] Clicar nos botões e verificar se eles mantém a funcionalidade proposta
- [ ] Aplicação não deve conter nenhum erro, warning ou console.log
- [ ] Alteração proposta no card foi implementada

2022-03-15 17:45 UTC, narukaioh requested changes

2022-03-15 17:45 UTC, narukaioh commented on src/pages/challenges/components/toggle-row/index.js
> +
A gente pode pensar em separar essas funções em um outro arquivo utilitário dentro da propria pasta desse componente, algo como helper.js e importar as funções que usamos de lá, isso vai deixar mais organizado esse arquivo de js do componente

2022-03-15 19:14 UTC, narukaioh requested changes

2022-03-15 19:14 UTC, narukaioh commented on src/pages/challenges/components/helper.js
> +/* export const getFeedback = (exercises, toggle) => {
esqueceram so de remover esse comentário

2022-03-16 12:39 UTC, narukaioh approved these changes

2022-03-16 13:55 UTC, nicoledbianchin approved these changes

2022-03-17 13:58 UTC, merged