Criar componentes
aceleradora-TW/acelera-mais-front pull request #91
Opened 2022-05-16 16:13 UTC by Cibely87

Criar Componentes
====

### 🆙 CHANGELOG

- Apresentação da lista de exercícios na tela de desafios deve ser de um exercício por linha, não mais agrupados por candidata.

## ⚠️ Me certifico que:

- [ ] Não deixei nenhum novo aviso, erro ou console.log nas minhas modificações
- [ ]  Fiz deploy para ambiente de teste certificando que o build não quebrou
- [ ]  Solicite uma revisão do código para 2 pessoas
- [ ]  Solicitei QA para 2 pessoas
- [ ]  Obtive aprovação de QA e posso fazer merge

## ⚠️ Como testar:

- [ ] Acessar link de teste: https://eluvya-acelera-mais-teste.herokuapp.com/ ;
- [ ] Fazer login (e-mail: ju@gmail.com, senha: 123456, nome da mentora: seu nome);
- [ ]  Clicar em um processo seletivo que contenha uma lista de exercício;
- [ ] Verificar se o layout da pagina apresenta este visual:
![image](https://user-images.githubusercontent.com/52509940/166695136-7d5630fa-0b96-41ac-9708-abc677a9cba8.png)
- [ ] Clicar nos botões e verificar se eles mantém a funcionalidade proposta;
- [ ] Aplicação não deve conter nenhum erro, warning ou console.log;
- [ ] Alteração proposta no card foi implementada

2022-05-19 18:09 UTC, narukaioh requested changes

2022-05-19 18:09 UTC, narukaioh commented on src/pages/challenges/components/toggle-row-exercise/helper.js
> +/* export const getStatusEvaluation = (evaluation) => {
ficou essa funcao comentada, precisa remover

2022-05-19 21:07 UTC, narukaioh approved these changes

2022-05-20 13:03 UTC, nicoledbianchin approved these changes

2022-05-20 16:26 UTC, merged