89/validacao dos dados de mentoras avaliadoras
aceleradora-TW/acelera-mais-front pull request #93
Opened 2022-05-25 17:41 UTC by drebarcelos

89/validacao dos dados de mentoras avaliadoras
====
  
### 🆙 CHANGELOG

Validacao dos componentes email e telefone.

## ⚠️ Me certifico que:

- [ ] Não deixei nenhum novo warning, erro ou console.log nas minhas modificações
- [ ] Fiz deploy para ambiente de teste certificando que o build não quebrou
- [ ] Solicitei **code review** para 2 pessoas

## ⚠️ Como testar:

- [ ]  Acessar repositorio frontend;
- [ ]  Ir para branch 89/validacao dos dados de mentoras avaliadoras;
- [ ]  Fazer o git pull;
- [ ]  Rodar yarn storybook;
- [ ]  Procurar e testar componentes email e telefone no storybook;
- [ ] Aplicação não deve conter nenhum erro, warning ou console.log
- [ ] Alteração proposta no card foi implementada

2022-05-25 17:53 UTC, narukaioh requested changes

2022-05-25 17:53 UTC, narukaioh commented on src/components/inputs/email/index.js
> +      setEmailError('')
se vc nao precisa passar nada nessa condição para emailError, vc nao precisa desse if e else, basta apenas verificar se o email é inválido

2022-05-25 17:53 UTC, narukaioh commented on src/components/inputs/email/email.stories.jsx
> +  onChange: () => { },
aqui voces declararam uma propriedade onChange, mas no parametro do componente InputEmail nao existe.

2022-05-25 18:04 UTC, Eduardo-LP commented on src/pages/authentication/forms/login/login.stories.jsx
> +// }
Arquivo ficou com código comentado. Tem algum proposito esses comentários irem nessa integração(merge)?

2022-05-25 18:16 UTC, Eduardo-LP approved these changes

2022-05-25 18:17 UTC, Cibely87 commented on src/components/inputs/email/index.js
> +      setEmailError('')
Alterações feitas

2022-05-25 18:21 UTC, narukaioh requested changes

2022-05-25 18:21 UTC, narukaioh commented on src/components/inputs/email/index.js
> +      setEmailError('Email valido!')
Não é necessário dizer que o email é valido, basta apenas ter a informação de que ela não é válida

if (!validator.isEmail(email)) {
    setEmailError("Email inválido")
}

2022-05-25 18:22 UTC, narukaioh commented on src/pages/authentication/forms/login/login.stories.jsx
> +// }
sim, estao comentadas pq ele está causando problemas q vao ser resolvidos em outro card

2022-05-26 19:35 UTC, narukaioh approved these changes

2022-05-27 13:22 UTC, nicoledbianchin approved these changes

2022-05-31 16:28 UTC, merged